# Generated by Django 3.1.3 on 2021-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
