# Generated by Django 3.1.5 on 2021-01-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='nazwa',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
