# Generated by Django 3.1.5 on 2021-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0002_auto_20210124_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
