# Generated by Django 3.1.5 on 2021-01-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0003_auto_20210124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('Przyjete', 'Male'), ('Przygotowywane', 'Female'), ('Gotowe do odebrania', 'Female')], default='Przyjete', max_length=20),
        ),
    ]
