# Generated by Django 3.1.5 on 2021-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0004_auto_20210124_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('Przyjete', 'Przyjete'), ('Przygotowywane', 'Przygotowywane'), ('Gotowe do odebrania', 'Gotowe do odebrania')], default='Przyjete', max_length=20),
        ),
    ]
