# Generated by Django 3.1.5 on 2021-01-24 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarnia', '0005_auto_20210124_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
